# Read about configuration here: https://jekyllrb.com/docs/configuration/options/
title: Daily Doots
description: 
keywords: ethereum, ethfinance, reddit, doots
url: https://dailydoots.com
permalink: pretty # Do not change this, it will break all links
timezone: America/New_York
markdown: kramdown
port: 4400
livereload: true

# Plugins
plugins:
  - jekyll-redirect-from # https://github.com/jekyll/jekyll-redirect-from
redirect_from: # jekyll-redirect-from
  json: false


defaults:
  - scope:
      path: "weekly/historical"
    values:
      weekly: true


# Assets
bootstrap_js: <script src="/assets/js/bootstrap.bundle.min.js"></script>
bootstrap_css: <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
# bootstrap_js: <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
# bootstrap_css: <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

