name: Update Data Daily

on:
  schedule:
    - cron: '10 */1 * * *'
    # - cron: '15 */07 * * *'
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    # - use: trstringer/manual-approval@v1
    
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r _scripts/requirements.txt
        
    - name: Fetch latest changes
      run: |
        git fetch origin main
        git reset --hard origin/main

    - name: Run Python script
      run: python _scripts/collect_data.py
      env:
        REDDIT_PROXY: ${{ secrets.REDDIT_PROXY }}
      
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add *
        git diff --quiet && git diff --staged --quiet || (git commit -m "[BOT] Update data" && git push https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }})
